### ISSUE TITLE
Adding New Airstack Examples for Recommendation

### ISSUE THREAD

**Issue by YosephKS** [dabit3/lens-algorithm-playground#1]
Hey Nader,

I'm working with Jason. Would like to contribute based on this tweet https://twitter.com/betashop/status/1675856226658205697

Currently, the Airstack Demo is only for getting a detailed Lens Profile, which only touches the surface.

More advanced functionality that can be added:

**Profile**

- [x] Get the address from the Lens profile – [docs](https://docs.airstack.xyz/airstack-docs-and-faqs/~/changes/RCZ9VCCIc7gOrsTvT2BI/use-cases/universal-resolver/lens)

**Recommendation**

- [x] Recommend based on NFTs (people in the same NFT community or DAOs) – [docs](https://docs.airstack.xyz/airstack-docs-and-faqs/~/changes/RCZ9VCCIc7gOrsTvT2BI/use-cases/recommendation-engine/recommendations-by-nfts)
- [x] Recommend based on POAPs (people that go to the same event) – [docs](https://docs.airstack.xyz/airstack-docs-and-faqs/~/changes/RCZ9VCCIc7gOrsTvT2BI/use-cases/recommendation-engine/recommendations-by-poaps)
- [x] Recommend based on Token Transfers (people that have a history) – [docs](https://docs.airstack.xyz/airstack-docs-and-faqs/~/changes/RCZ9VCCIc7gOrsTvT2BI/use-cases/recommendation-engine/recommendations-by-token-transfers)

I'll be making a PR on this in the next few days, but feel free to provide any comments~

**Comment by dabit3** [comment]
This would be awesome, would love to see a PR for this!

**Comment by YosephKS** [comment]
Great thanks @dabit3!

Seems like the PR https://github.com/dabit3/lens-algorithm-playground/pull/2 already merged, so closing this issue
